service: display_power_switcher

plugins:
  - serverless-offline
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-1
  stage: ${opt:stage, self:custom.defaultStage}
  profile: ${opt:profile, self:custom.defaultProfile}
  stackName: ${self:service}-${self:provider.stage}
  environment:
    AUTH_TOKEN: ${env:AUTH_TOKEN}
    DEVICE_ID: ${env:DEVICE_ID}
    SWITCHBOT_TOKEN: ${env:SWITCHBOT_TOKEN}

custom:
  defaultStage: dev
  defaultProfile: default
  webpack:
    webpackConfig: 'webpack/webpack.config.js'
    includeModules: true
#  environment:
#    dev: ${file(./serverless/config/dev.yml)}
#    stage: ${file(./serverless/config/stage.yml)}
#    prod: ${file(./serverless/config/prod.yml)}

functions:
  app:
    handler: src/apigw.handler
    timeout: 30
    events:
      - http:
          path: /
          method: any
      - http:
          path: /{proxy+}
          method: any


#package:
#  exclude:
#    - '**'
#  include:
#    - dist/**