name: Serverless deploy

on:
  push:
    branch:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install nodejs
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: install dependencies
        run: |
          npm install serverless -g
          npm install

      - name: sls deploy
        run: sls deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
          DEVICE_ID: ${{ secrets.DEVICE_ID }}
          SWITCHBOT_TOKEN: ${{ secrets.SWITCHBOT_TOKEN }}