name: Serverless deploy

on:
  push:
    branch:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install nodejs
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: install dependencies
        run: |
          npm install

      - name: serverless deploy
        uses: serverless/github-action@v2
        with:
          args: deploy
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
          DEVICE_ID: ${{ secrets.DEVICE_ID }}
          SWITCHBOT_TOKEN: ${{ secrets.SWITCHBOT_TOKEN }}
          AWS_SDK_LOAD_CONFIG: 0
